In [ ]:
# part -7

In [3]:
import numpy as np

In [ ]:
# random

In [4]:
np.random.random(1)

array([0.04043045])

In [6]:
np.random.random((2,2))

array([[0.96694569, 0.78867186],
       [0.24210463, 0.72880648]])

In [7]:
np.random.randint((1,10))

array([0, 1])

In [10]:
np.random.randint(1,10,(2,2))

array([[3, 6],
       [6, 5]])

In [13]:
np.random.randint(1,10,(3,4,5))

array([[[1, 8, 3, 6, 4],
        [1, 3, 3, 8, 1],
        [2, 7, 4, 1, 4],
        [2, 7, 8, 6, 3]],

       [[6, 6, 4, 6, 4],
        [8, 5, 5, 6, 9],
        [4, 6, 5, 1, 8],
        [7, 2, 1, 3, 8]],

       [[4, 9, 3, 9, 7],
        [6, 3, 7, 3, 2],
        [2, 3, 5, 2, 1],
        [3, 4, 3, 1, 2]]])

In [14]:
np.random.rand(2,2)

array([[0.65380018, 0.64279053],
       [0.79392647, 0.51888741]])

In [15]:
np.random.randn(2,2)

array([[ 1.00978215, -1.68360427],
       [ 0.8258432 , -0.28739129]])

In [16]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.random.choice(a)

4

In [18]:
np.random.choice(a)

2