In [ ]:
# part - 4

In [37]:
import numpy as np

In [38]:
a=np.arange(1,51)
a.reshape(10,5) #(col,row)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [18]:
print(a[2:3])

[3]


In [23]:
a[0:5]

array([1, 2, 3, 4, 5])

In [29]:
a[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
a[:4].dtype

dtype('int64')