In [5]:
import numpy as np

In [3]:
lst=[1,2,3,4,5,6] # to declare a list 
print(lst)

[1, 2, 3, 4, 5, 6]


In [11]:
# 1-D Array
print("1-D Array\n")
a=np.array([1,2,3,4,5]) # to declare a 1 D Array
print(a)
print(type(a))


1-D Array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
print("2-D Array\n")
b=np.array([[1,2,3,4,5], # to declare a 2 D Array
           [6,7,8,9,10]])
print(b)
print(type(b))

2-D Array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [27]:
print("3-D Array\n")
c=np.array([[[1,2,3,4,5], # to declare a 3 D Array
           [6,7,8,9,10],
           [11,12,13,14,15],
           ]])

print(b)
print()
print(type(b)) #get type of array


3-D Array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

<class 'numpy.ndarray'>


In [24]:
print(a.size) # print the size of array

print(b.size)
print(c.size)


5
10
15


In [28]:
print(a.shape) # print rows and column

print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [29]:
# dtype :- Type of Data Present in the array

print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [42]:
c.transpose()

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])