In [6]:
import numpy as np
arr = np.array([[ 1,  2,  3],
                [ 3, 45,  6],
                [ 4,  5,  6]])
arr


array([[ 1,  2,  3],
       [ 3, 45,  6],
       [ 4,  5,  6]])

In [21]:
print(arr.T)

[[ 1  3  4]
 [ 2 45  5]
 [ 3  6  6]]


In [24]:
for i in arr.flat: # for print one by one in array
    print(i)

1
2
3
3
45
6
4
5
6


In [26]:
a=np.arange(99)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98


In [28]:
a.nbytes

792

In [7]:
two=np.array([[1,2,3,4,5]])
two

array([[1, 2, 3, 4, 5]])

In [9]:
print(two.max)
print(two.min)
print(two.argsort())


<built-in method max of numpy.ndarray object at 0x113681830>
<built-in method min of numpy.ndarray object at 0x113681830>
[[0 1 2 3 4]]


In [11]:
print(arr.sort())

None


In [15]:
ar1=np.array([1,2,3,4])
ar2=np.array([5,6,7,8])

np.add(ar1,ar2)


array([ 6,  8, 10, 12])

In [16]:
print(np.subtract(ar1,ar2))

[-4 -4 -4 -4]


In [17]:
np.sqrt(ar1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [19]:
np.divide(ar1,ar2)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [20]:
np.multiply(ar1,ar2)

array([ 5, 12, 21, 32])

In [21]:
np.power(ar1,3)

array([ 1,  8, 27, 64])

In [22]:
# combining and spliting arrays

a=[1,2,3,4,5]
b=[6,7,8,9,0]
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [31]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,0])
print(a+b)
print(np.concatenate([a,b]))


[ 7  9 11 13  5]
[1 2 3 4 5 6 7 8 9 0]


In [43]:
c=np.array([[1,2,3],[3,4,5],[6,7,8]])
d=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(np.concatenate((c,d)))


[[1 2 3]
 [3 4 5]
 [6 7 8]
 [1 2 3]
 [3 4 5]
 [6 7 8]]


In [44]:
print(np.hstack([c,d])) #horizantal concetation

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


In [47]:
print(np.vstack([c,d])) #vertical concetation

[[1 2 3]
 [3 4 5]
 [6 7 8]
 [1 2 3]
 [3 4 5]
 [6 7 8]]


In [51]:
arr=np.array([1,2,3,4,5,6,7,8,9])
k=np.array_split(arr,3)
k

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [52]:
p=np.array_split(arr,2)
p

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

In [55]:
q=np.array_split(arr,5)
q
q[1]

array([3, 4])

In [57]:
# adding and removing 
print(np.append(arr,100))
print(np.append(arr,[200,9]))

[  1   2   3   4   5   6   7   8   9 100]
[  1   2   3   4   5   6   7   8   9 200   9]


In [58]:
print(np.insert(arr,1,50))

[ 1 50  2  3  4  5  6  7  8  9]


In [59]:
print(np.insert(arr,4,1))

[1 2 3 4 1 5 6 7 8 9]


In [68]:
mul=([[50,40],[30,20],[10,80]])
print(np.insert(mul,0,[10,11],axis=0))

[[10 11]
 [50 40]
 [30 20]
 [10 80]]


In [70]:
print(np.delete(mul,0,axis=1))# remove vertical 

[[40]
 [20]
 [80]]


In [72]:
print(mul)

[[50, 40], [30, 20], [10, 80]]


In [73]:
print(np.delete(mul,0,axis=0)) #remove vertically

[[30 20]
 [10 80]]
