In [4]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5] )

# Perform an operation
print("Array:", arr)
print("Sum of elements:", np.sum(arr))

Array: [1 2 3 4 5]
Sum of elements: 15


In [5]:
print([arr])

[array([1, 2, 3, 4, 5])]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr[2]

<function int64.any>

In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a[1]

array([4, 5, 6])

In [14]:
a[0]

array([1, 2, 3])

In [15]:
a.shape

(3, 3)

In [16]:
a.dtype

dtype('int64')

In [18]:
a[1,2]=65
a

array([[ 1,  2,  3],
       [ 4,  5, 65],
       [ 7,  8,  9]])

In [19]:
print(a)

[[ 1  2  3]
 [ 4  5 65]
 [ 7  8  9]]


In [24]:
a[1,1]=98
a

array([[ 1,  2,  3],
       [ 4, 98, 98],
       [ 7,  8, 98]])

In [25]:
print(a)

[[ 1  2  3]
 [ 4 98 98]
 [ 7  8 98]]


In [29]:
a[0,1]=8
a

array([[ 7,  8,  3],
       [ 4, 98, 98],
       [ 7,  8, 98]])

In [33]:
a[1,2]=9
a

array([[ 7,  8,  3],
       [ 4, 89,  9],
       [ 7,  8, 98]])

In [34]:
a[1]

array([ 4, 89,  9])

In [35]:
np.array([[1,2,3,4],[5,67,8,9]])

array([[ 1,  2,  3,  4],
       [ 5, 67,  8,  9]])

In [38]:
list=[1,2,3,4]
con=np.array(list)
print(con)
print(type(con))

[1 2 3 4]
<class 'numpy.ndarray'>


In [41]:
print(list)

[1, 2, 3, 4]


In [45]:
t=(1,2,3,4)
a=np.array(t)
print(type(a))

<class 'numpy.ndarray'>


In [57]:
z=np.ones((3,3))
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
a=np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
a=np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
a.shape

(5, 3)

In [59]:
a.dtype

dtype('float64')

In [64]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [65]:
print(type(a))

<class 'numpy.ndarray'>


In [66]:
a.shape

(2, 2)

In [67]:
a.dtype

dtype('float64')

In [71]:
rng=np.arange(12)
rng

array([1, 5, 9])

In [73]:
rng=np.arange(1,120000,3)
rng

array([     1,      4,      7, ..., 119992, 119995, 119998])

In [81]:
emp=np.empty((2,3))
emp

array([[1., 1., 1.],
       [1., 1., 1.]])

In [89]:
a=np.identity(300) # when we use create big array that time we use identity
a

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [90]:
a.shape

(300, 300)

In [91]:
a.size

90000

In [92]:
a.dtype

dtype('float64')

In [100]:
a=np.arange(99)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [107]:
ar=a.reshape(3,33)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [1]:
rav=a.ravel()
rav

NameError: name 'a' is not defined

In [109]:
print(type(a))

<class 'numpy.ndarray'>


In [110]:
a.size

99

In [111]:
a.any

<function ndarray.any>

In [112]:
a.shape

(99,)

In [114]:
n=[[1,2,3],[3,45,6],[4,5,6]]
n
print(type(n))

<class 'list'>


In [124]:
arr=np.array(n)
arr

array([[ 1,  2,  3],
       [ 3, 45,  6],
       [ 4,  5,  6]])

In [128]:
arr.sum(axis=0) #vertical sum

array([ 8, 52, 15])

In [129]:
arr.sum(axis=1) #horizontal sum

array([ 6, 54, 15])

In [131]:
# o is row & 1 is column

In [132]:
list1=[1,2,3,4,5]
print(list1)
print(type(list1))
conve=np.array(list1)
print(conve)
print(type(conve))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

weight = np.array([74.2, 75, 87, 15, 90, 45, 30, 50, 60, 99])

filtered_weights = weight[weight > 68]
print(filtered_weights)


[74.2 75.  87.  90.  99. ]
