In [12]:
import numpy as np

#1 create a list and covert it into in array
list_temp=[3.04,1.65,5.78,1.66,1.64,4.67]
a=np.array([list_temp])
print(a)
print(type(a))

[[3.04 1.65 5.78 1.66 1.64 4.67]]
<class 'numpy.ndarray'>


In [6]:
weight=[74.2,85,74,67.9,52,70.5,86,51.8,64,82]
a=np.array([weight])
fa=a>68
new=a[fa]
print(new)

[74.2 85.  74.  70.5 86.  82. ]


In [27]:
b=np.random.randint(20,41)
np.random.seed(21)
print(b)

29


In [29]:
import numpy as np

a=np.arange(1,10)

power = a **5
print(power)

[    1    32   243  1024  3125  7776 16807 32768 59049]


In [36]:
import numpy as np
b = np.arange(50, 100, 2)  # Generates numbers from 50 to 98 with step size 2
print(b)


[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [40]:
A=[[1,2,3],[4,5,6],[7,8,9]]

a=np.array(A)
sum=np.sum(a,axis=1)
print(sum)


[ 6 15 24]


In [49]:
A=[[31,12,53],[64,85,96],[37,28,19]]
a=np.array(A)
rem=np.remainder(a,8)
print(rem)

[[7 4 5]
 [0 5 0]
 [5 4 3]]


In [53]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
b=a.reshape(4,5)
print(b)
print(type(b))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
<class 'numpy.ndarray'>


In [59]:
price_monday=[5,20,30,40,50]
price_tuesday=[5,15,20,35,45]
insertion=np.intersect1d(price_monday,price_tuesday)
print(insertion)

[ 5 20]


In [62]:
def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    return bmi

weight = float(input("Enter weight in kilograms: "))
height = float(input("Enter height in meters: "))

bmi = calculate_bmi(weight, height)

print(f"Your BMI is: {bmi:.2f}")


Your BMI is: 22.86


In [63]:
arr=np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
m=[[1,2,3],[4,5,6],[7,8,9]]
print(m)
a=np.transpose(m)
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [68]:
import numpy as np


array = np.array([6,5,3,15])


def apply_function(x):
    return (2 * x - 1) * (x + 5)

result = np.array([apply_function(x) for x in array])


print(result)


[121  90  40 580]


In [70]:
array = np.array([6,5,3,15])

for x in array:
    print((2 * x - 1) * (x + 5))

121
90
40
580


In [72]:
import numpy as np


num_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


min_value = np.min(num_arr)


print(min_value)


1


In [81]:
import numpy as np

num_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(num_arr)
print("\n")
repl = np.where(num_arr % 2 != 0, -2, num_arr)

print(repl)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[-2  2 -2  4]
 [-2  6 -2  8]
 [-2 10 -2 12]]


In [1]:
# 4. replace all odd numbers in the array with -2 without changing the original array

import numpy as np

num_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(num_arr)
print("\n")
repl = np.where(num_arr % 2 == 0, -2, num_arr)

print(repl)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 1 -2  3 -2]
 [ 5 -2  7 -2]
 [ 9 -2 11 -2]]


In [6]:
#5 stack two arrays vertically
import numpy as np

# Define two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1)
print(array2)
print("\n")

# Stack vertically
result = np.vstack((array1, array2))

print(result)


[1 2 3]
[4 5 6]


[[1 2 3]
 [4 5 6]]


In [7]:
# 6. get common items between two python numpy two arrays

array1 = [1, 2, 3, 4]
array2 = [3, 4, 5, 6]

common_elements = list(set(array1) & set(array2))
print(common_elements)

[3, 4]


In [8]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = np.array([3, 4, 5, 6])

common_elements = np.intersect1d(array1, array2)

print(common_elements)

[3 4]


In [9]:
# 7.remove all the elemnts from the array1 that are present in the array2

array1 = [1, 2, 3, 4, 5]
array2 = [3, 4]

result = list(filter(lambda x: x not in array2, array1))

print(result)

[1, 2, 5]


In [11]:
# 8. get the positions where elements of two arrays match

import numpy as np 

array1 = np.array([1,2,3,4,5])
array2=np.array([0,1,3,4,5])
postion =np.where(array1==array2)[0]
print(postion)


[2 3 4]


In [13]:
# 9. reverse each of the rows of a 2D array 

import numpy as np


array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

reversed_rows = np.flip(array, axis=1)

print(reversed_rows)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [14]:
# 10 . swap row 1 and row 2 in a given array

import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

temp = array[0].copy()
array[0] = array[1]
array[1] = temp

print(array)


[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [15]:
# 11 write a program to add new column 5 & 7 at the postion given in the array

import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

new_column = np.array([[5], [7], [9]])

position = 1 

result = np.insert(array, position, new_column, axis=1)

print("Original Array:")
print(array)

print("\nArray After Adding New Column:")
print(result)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array After Adding New Column:
[[1 5 7 9 2 3]
 [4 5 7 9 5 6]
 [7 5 7 9 8 9]]


In [16]:
# 12 write a code  to combine  horizantolly two arrays

import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])


combined_array = np.hstack((array1, array2))

print("Combined Array:")
print(combined_array)


Combined Array:
[1 2 3 4 5 6]


In [18]:
# 13 write a program to divide array into sub arrays containning equal number of column

import numpy as np

# Define a 2D array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

num_columns_per_subarray = 2

sub_arrays = np.hsplit(array, array.shape[1] // num_columns_per_subarray)

for i, sub_array in enumerate(sub_arrays):
    print(f"Sub-array {i + 1}:")
    print(sub_array)
    print()


Sub-array 1:
[[ 1  2]
 [ 5  6]
 [ 9 10]]

Sub-array 2:
[[ 3  4]
 [ 7  8]
 [11 12]]

