In [61]:
#search sort and filter arrays

import numpy as np
s=([11,2,34,41,57])
print(s)
np.sort(s)

[11, 2, 34, 41, 57]


array([ 2, 11, 34, 41, 57])

In [62]:
arr=np.array([[11,1,33],[21,33,32]])
arr
print(np.sort(arr))

[[ 1 11 33]
 [21 32 33]]


In [63]:
search=np.array([[1,2,3]])
print(np.where(search%2==0))


(array([0]), array([1]))


In [64]:
s=np.array([7,8,4,3,12,2])
s1=np.where(s==4)
print(s1)
s2=np.where(s%2==0)
print(s2)


(array([2]),)
(array([1, 2, 4, 5]),)


In [65]:
s=np.array([22,34,63,98])
ss=np.searchsorted(s,8)
print(ss)

0


In [66]:
#array filter

s=np.array([7,8,4,3])
fa=[True,False,True,False]
new=s[fa]
print(new)

[7 4]


In [67]:
import numpy as np
s=np.array([7,8,4,3])
fa=s>3
new=s[fa]
print(new)

[7 8 4]


In [68]:
import numpy as np
s=np.array([7,8,4,3])
fa=s%2==0
new=s[fa]
print(new)

[8 4]


In [69]:
import numpy as np
s=np.array([7,8,4,3])
fa=s%2!=0
new=s[fa]
print(new)

[7 3]


In [70]:
import numpy as np
s=np.array([7,8,4,3])
fa=s<3
new=s[fa]
print(new)

[]


In [71]:
import numpy as np
s=np.array([7,8,4,3])
fa=s==3
new=s[fa]
print(new)

[3]


In [72]:
#aggregate function

a=([10,2,3,20])
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a)) #previous value sum

[10, 2, 3, 20]
35
2
20
4
8.75
[10 12 15 35]


In [73]:
import numpy as np

# Define price and quantity
price = np.array([2, 4, 5, 6, 7])  # Assuming you meant c
quantity = np.array([100, 200, 300, 400, 500])

# Print price and quantity
print("Price:\n", price)
print("Quantity:\n", quantity)

# Calculate price sum
price_sum = np.sum(price)
print("Price Sum:", price_sum)

# Element-wise multiplication of price and quantity
cum = price * quantity  # Multiply price by quantity
print("Price * Quantity:\n", cum)


Price:
 [2 4 5 6 7]
Quantity:
 [100 200 300 400 500]
Price Sum: 24
Price * Quantity:
 [ 200  800 1500 2400 3500]


In [74]:
import statistics as stats

backend_food=[200,210,300,350,200,280,320]
print(backend_food)
a=np.array(backend_food)

[200, 210, 300, 350, 200, 280, 320]


In [75]:
print(np.mean(backend_food))

265.7142857142857


In [76]:
print(np.median(backend_food))

280.0


In [77]:
print(stats.mode(backend_food))

200


In [78]:
print(np.std(backend_food))

57.53437304457791


In [79]:
print(np.var(backend_food))

3310.204081632653


In [80]:
57 **2

3249